version: '3.1'

services:
  mysql:
    container_name: sample-mysql
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'sample'
      MYSQL_USER: 'sample'
      MYSQL_PASS: 'sample'
    volumes:
      - /opt/mysql_data:/var/lib/mysql
      - ./sqldump:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  zookeeper:
    container_name: sample-zookeeper
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'

  kafka:
    container_name: sample-kafka
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_CREATE_TOPICS: 'sample:1:1'
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  redis:
    container_name: sample-redis
    image: redis:7.0.4
    ports:
      - 6379:6379
