apiVersion: v1
kind: Service
metadata:
  name: {{ include "member-api.fullname" . }}-blue
  labels:
    {{- include "member-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
      name: http
  selector:
    {{- include "member-api.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "member-api.fullname" . }}-green
  labels:
    {{- include "member-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
      name: http
  selector:
    {{- include "member-api.selectorLabels" . | nindent 4 }}
