apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coupon-api.fullname" . }}
data:
  serverPort: '8080'
  dbHost: 'database-2.cluster-cvinkzp4mhyj.ap-northeast-2.rds.amazonaws.com'
  dbPort: '3306'
  dbName: 'sample'
  dbDdlauto: 'update'
  kafkaHost: 'kafka-0.kafka-headless.dev.svc.cluster.local'
  kafkaPort: '9092'
