{{- $fullName := include "coupon-api.fullname" . -}}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ $fullName }}
spec:
  host: {{ $fullName }}.{{ .Release.Namespace }}.svc.cluster.local
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary
