apiVersion: v1
kind: Service
metadata:
  name: {{ include "coupon-api.fullname" . }}
  labels:
    {{- include "coupon-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
      name: http
  selector:
    {{- include "coupon-api.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "coupon-api.fullname" . }}-canary
  labels:
    {{- include "coupon-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
      name: http
  selector:
    {{- include "coupon-api.selectorLabels" . | nindent 4 }}
