{{- $fullName := include "coupon-api.fullname" . -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
spec:
  hosts:
  {{- range .Values.ingress.hosts }}
  - {{ .host | quote }}
  {{- end }}
  - "{{ $fullName }}.{{ .Release.Namespace }}.svc.cluster.local"
  gateways:
  - {{ $fullName }}
  http:
  - route:
    - destination:
        host: "{{ $fullName }}.{{ .Release.Namespace }}.svc.cluster.local"
        subset: stable
      weight: 100
    - destination:
        host: "{{ $fullName }}.{{ .Release.Namespace }}.svc.cluster.local"
        subset: canary
      weight: 0
